// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using HistoryExport_EBI.Domain.Entities;
using HistoryExport_EBI.Infrastructure.Persistence.DbMappings;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace HistoryExport_EBI.Infrastructure.Persistence;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<History1hour> History1hour { get; set; }

    public virtual DbSet<History1min> History1min { get; set; }

    public virtual DbSet<History5sec> History5sec { get; set; }

    public virtual DbSet<Parameter> Parameters { get; set; }

    public virtual DbSet<Point> Points { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
