// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HistoryExport_EBI.Domain.Entities;
using HistoryExport_EBI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace HistoryExport_EBI.Infrastructure.Persistence.DbMappings
{
    public partial class History5secDbMappings : IEntityTypeConfiguration<History5sec>
    {
        public void Configure(EntityTypeBuilder<History5sec> entity)
        {
            entity.HasKey(e => new { e.PointId, e.Usttimestamp });

            entity.ToTable("History_5sec");

            entity.HasIndex(e => e.Usttimestamp, "IX_History_5sec");

            entity.Property(e => e.Usttimestamp)
                .HasColumnType("datetime")
                .HasColumnName("USTTimestamp");
            entity.Property(e => e.Timestamp).HasColumnType("datetime");

            entity.HasOne(d => d.Point).WithMany(p => p.History5secs)
                .HasForeignKey(d => d.PointId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_History_5sec_Point");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<History5sec> entity);
    }
}
