// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HistoryExport_EBI.Domain.Entities;
using HistoryExport_EBI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace HistoryExport_EBI.Infrastructure.Persistence.DbMappings
{
    public partial class ParameterDbMappings : IEntityTypeConfiguration<Parameter>
    {
        public void Configure(EntityTypeBuilder<Parameter> entity)
        {
            entity.HasKey(e => e.Name);

            entity.ToTable("Parameter");

            entity.Property(e => e.Name).HasMaxLength(30);
            entity.Property(e => e.Comment).HasMaxLength(100);
            entity.Property(e => e.Value).HasMaxLength(20);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Parameter> entity);
    }
}
