// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using HistoryExport_EBI.Domain.Entities;
using HistoryExport_EBI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace HistoryExport_EBI.Infrastructure.Persistence.DbMappings
{
    public partial class PointDbMappings : IEntityTypeConfiguration<Point>
    {
        public void Configure(EntityTypeBuilder<Point> entity)
        {
            entity.HasKey(e => e.PointId).HasName("PK_Points");

            entity.ToTable("Point");

            entity.HasIndex(e => new { e.PointName, e.ParamName }, "IX_Name").IsUnique();

            entity.Property(e => e.PointId).ValueGeneratedNever();
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Device).HasMaxLength(100);
            entity.Property(e => e.ParamName).HasMaxLength(50);
            entity.Property(e => e.PointName).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Point> entity);
    }
}
